plugins:
  signup_enabled:
    default: true
    client: true
  signup_maximum_options:
    default: 4
    client: true
  signup_voters_text_one:
    default: "person"
    client: true
  signup_voters_text_other:
    default: "people"
    client: true
